liquida2018/bcp/urls.py
"""
Module: Barcode Printer URLS
Project: Django BCP
Copyright: Adlibre Pty Ltd 2012
License: See LICENSE for license information
"""

from django.conf.urls import url
from . import views
from django.contrib.auth.views import *
from django.urls import path, re_path
#import mdtui.views

app_name = 'bcp'

urlpatterns = [
    re_path(r'^(?P<numerodocumento>[-\w]+)/(?P<code>[\w-]+)$', views.generate, name='generate'),
    re_path(r'^(?P<barcode_type>(Standard39|Code128))/(?P<code>[\w-]+)/print$', views.print_barcode, name='print'),
    re_path(r'^(?P<numerodocumento>[-\w]+)/(?P<code>[\w-]+)/print_qrcode$', views.print_qrcode, name='print_qrcode'),
    re_path(r'^(?P<barcode_type>(Standard39|Code128))/(?P<code>[\w-]+)/test', views.print_barcode_embed_example, name='embed-example'),
]

liquida2018/liquida2018/urls.py
"""liquida2018 URL Configuration
"""
from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from participante import urls as purls
from lojista import urls as lurls
from cupom import urls as curls
from bcp import urls as burls

handler404 = 'participante.views.not_found_page_view'

urlpatterns = [
    path('', include(purls)),
    path('nimda/', admin.site.urls),
    url('cupom/', include(curls, namespace='cupom')),
    path('lojista/', include(lurls, namespace='lojista')),
    path('barcode/', include(burls, namespace='bcp')),
    # python-social-auth
    #url('social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

liquida2018/lojista/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views
from django_filters.views import FilterView
from .filters import LojistaFilter

app_name = 'lojista'

urlpatterns = [
    # Lojistas urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('list/', views.lojistalist, name='list'),
    re_path(r'^edit/(?P<ielojista>[\d,.?!]+)/$', views.editlojista, name='editlojista'),
    # path('search/', FilterView.as_view(filterset_class=LojistaFilter,
    #     template_name='lojista/lojistas_list.html'), name='search'),
    path('search/', views.search, name='search'),
    path('cupons/', views.cupons, name='cupons'),
    #re_path(r'^search/(?P<cpf>[-\w]+)$', views.search_cpf, name='searchbycpf'),
    # Ramo de atividades pathpatterns
    path('registeratividade/', views.registeratividade, name='registeratividade'),
    path('listatividade/', views.listatividade, name='listatividade'),
]

liquida2018/participante/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import *
from django.urls import path, re_path
from django_filters.views import FilterView
from .filters import UserFilter
from .models import Profile


app_name = 'participante'
handler404 = 'views.not_found_page_view'

urlpatterns = [
    # url(r'^login/$', views.user_login, name='login'),
    path('', views.homepage, name='homepage'),
    path('dash/', views.dashboard, name='dashboard'),
    #path('lojista/', views.lojista, name='notfound'),
    # path('search/', FilterView.as_view(filterset_class=UserFilter,
    #     template_name='participante/participante_list.html'), name='search'),
    path('search/', views.search, name='search'),
    path('participante/cpf', views.search_by_cpf, name='search_by_cpf'),

    url(r'^list$', views.participante_list, name='list'),


    re_path(r'^participante/(?P<username>[-\w]+)/detail$', views.user_detail, name='user_detail'),
    re_path(r'^participante/edit/(?P<username>[-\w]+)/$', views.user_edit, name='user_edit'),
    # Coupons paths
    path('docsfiscais/', views.doclist, name='docsfiscais'),

    # Coupons paths
    path('coupons/', views.coupons, name='coupons'),

    # Premios paths
    path('premios/', views.premios, name='premios'),


    path('cadastrar/', views.register, name='register'),
    path('register/', views.register2, name='register-op'),
    path('edit/', views.edit, name='edit'),

    # Documentos Fiscais paths
    path('adddocfiscal/', views.adddocfiscal, name='adddocfiscal'),
    re_path(r'^adddocfiscal/(?P<username>[-\w]+)/$', views.adddocfiscalbyop, name='adddocfiscalbyop'),
    path('editdocfiscal/', views.editdocfiscal, name='editdocfiscal'),
    re_path(r'^editdocfiscal/(?P<numerodocumento>[\d,.?!]+)/$', views.editdocfiscal, name='editdocfiscal'),
    re_path(r'^validadocfiscal/(?P<numerodocumento>[\d,.?!]+)/$', views.validadocfiscal, name='validadocfiscal'),

    # login / logout paths
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('logout-then-login/', logout_then_login, name='logout_then_login'),

    # change password paths
    path('password-change/',password_change, name='password_change'),
    path('password-change/done/', password_change_done, name='password_change_done'),

    # restore password paths
    path('password-reset/', password_reset, name='password_reset'),
    path('password-reset/done/', password_reset_done, name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', password_reset_confirm, name='password_reset_confirm'),
    path('password-reset/complete/', password_reset_complete, name='password_reset_complete'),


]

liquida2018/lojista/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django_currentuser.db.models import CurrentUserField
from django.urls import reverse

class RamoAtividade(models.Model):
    """
    Model representando o ramo de atividade.
    """
    atividade = models.CharField(max_length=80, help_text='Informe o Ramo de Atividade. (exemplo: alimentação, vestuário, restaurante, etc.)')
    dataCadastro    = models.DateTimeField(verbose_name=u'Cadastrado em', auto_now_add=True, editable=False)   #nao vai aparecer na tela
    CadastradoPor   = CurrentUserField(verbose_name=u'Cadastrado Por', editable=False)
#    DataAlteracao   = models.DateTimeField(verbose_name=u'Alterado em', auto_now_add=True) #nao vai aparecer na tela
#    AlteradoPor_Id   = models.ForeignKey(User, blank=False, related_name='Cadastrado_por', editable=False, default=current_user.get_current_user)
    ativo = models.BooleanField(default=True)

    exclude =('ativo')

    class Meta:
        ordering = ['atividade']
        verbose_name = (u'ramo de Atividade')
        verbose_name_plural = (u'ramos de Atividades')

    def __str__(self):
        """
        String representando o Model object (in Admin site etc.)
        """
        return self.atividade


class Lojista(models.Model):
    CNPJLojista     = models.CharField(verbose_name=u'CNPJ do Lojista*', max_length=18, blank=False, null=True, unique=True, help_text=u'ex. 00.000.000/0000-00')
    IELojista       = models.CharField(verbose_name=u'Inscrição Estadual*', max_length=14, blank=True, unique=True)
    razaoLojista    = models.CharField(verbose_name=u'Razão Social*', max_length=70, blank=True, null=True, help_text=u'Razão Social')
    fantasiaLojista = models.CharField(verbose_name=u'Nome Fantasia*', max_length=70, blank=False, help_text=u'Nome Fantasia')
    ramoAtividade   = models.ForeignKey('RamoAtividade', verbose_name=u'Ramo de Atividade*', on_delete=models.SET_NULL, null=True)
    dataCadastro    = models.DateTimeField(verbose_name=u'Cadastrado em', auto_now_add=True, editable=False)   #nao vai aparecer na tela
    CadastradoPor   = CurrentUserField(verbose_name=u'Cadastrado Por', editable=False)
#    CadastradoPor_Id = models.ForeignKey(User, editable=False, default=User.pk, on_delete=models.SET_NULL, null=True)
#    CadastradoPor_Id = models.ForeignKey(User, blank=False, related_name='Cadastrado_por', editable=False, default=current_user.get_current_user)
#    DataAlteracao   = models.DateTimeField(verbose_name=u'Alterado em', auto_now_add=True) #nao vai aparecer na tela
#    AlteradoPor_Id   = models.ForeignKey(User, blank=False, related_name='Cadastrado_por', editable=False, default=current_user.get_current_user)
    ativo           = models.BooleanField(default=True)

    exclude =('ativo')

    class Meta:
        ordering = ['fantasiaLojista']
        verbose_name = (u'lojista')
        verbose_name_plural = (u'lojistas')


    def __str__(self):
        """
        String representando o Objeto Participante.
        """
        return self.fantasiaLojista

    def get_absolute_url(self):
        return reverse('lojista:editlojista', args=[self.IELojista])

liquida2018/lojista/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Lojista, RamoAtividade
from localflavor.br.forms import *

class LojistaRegistrationForm(forms.ModelForm):
    CNPJLojista = BRCNPJField(label='CNPJ*', required=True, max_length=18, widget=forms.TextInput(attrs={'class':'cnpj'}))
    ramoAtividade =  forms.Select(attrs={'class':'form-group'}) 
    class Meta:
        model = Lojista
        fields = '__all__'
        widgets = {
            'ativo': forms.HiddenInput,
            'CadastradoPor': forms.HiddenInput,
        }

class RamoAtividadeRegistrationForm(forms.ModelForm):

    class Meta:
        model = RamoAtividade
        fields = '__all__'
        widgets = {
            'CadastradoPor': forms.HiddenInput,
        }

liquida2018/lojista/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import LojistaRegistrationForm, RamoAtividadeRegistrationForm
from .models import Lojista, RamoAtividade
from django.contrib.auth.decorators import user_passes_test
from .filters import LojistaFilter
from django.db.models.functions import Lower, Upper
from cupom.models import Cupom
from participante.models import Profile
from django.contrib.auth.models import User

@login_required
@user_passes_test(lambda u: u.is_superuser)
def cupons(request):
    if(request.GET.get('q')):
        if 'q' in request.GET is not None:
            cpf = request.GET.get('q')
            profile = get_object_or_404(Profile, CPF=cpf)
            user = get_object_or_404(User, username= profile.user.username)
            cupons = Cupom.objects.filter(user=user)
            return render(request, 'lojista/cupons.html', {'section': 'cupons','user': profile, 'cupons': cupons})
        else:
            messages.error(request, 'CPF não encontrado!')
    return render(request, 'lojista/search_by_cpf.html')

@login_required
@user_passes_test(lambda u: u.is_superuser)
def search(request):
      lojista_list = Lojista.objects.all().order_by(Upper('fantasiaLojista').asc())
      lojista_filter = LojistaFilter(request.GET, queryset=lojista_list)
      return render(request, 'lojista/lojistas_list.html', {'filter': lojista_filter,
                                                                     'section':'lojistas'})

@login_required
@user_passes_test(lambda u: u.is_superuser)
def homepage(request):
    return render(request, 'lojista/dashboard.html', {'section': 'lojista'})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def register(request):
    if request.method == 'POST':
        lojista_form = LojistaRegistrationForm(request.POST)
        if lojista_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_lojista = lojista_form.save(commit=False)
            # Save the User object
            new_lojista.save()
            return render(request,
                          'lojista/register_done.html',
                          {'new_lojista': new_lojista})

    else:
        lojista_form = LojistaRegistrationForm()
    return render(request, 'lojista/register.html', {'lojista_form': lojista_form   })

@login_required
@user_passes_test(lambda u: u.is_superuser)
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Perfil atualizado com sucesso')
        else:
            messages.error(request, 'Erro na atualização do perfil')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'participante/edit.html', {'user_form': user_form,
                                                 'profile_form': profile_form})

@login_required
def editlojista(request, ielojista):
    if request.method == 'POST':
        instance = get_object_or_404(Lojista, IELojista=ielojista)
        lojista_form = LojistaRegistrationForm(instance=instance)
        if lojista_form.is_valid():
            lojista_form.save()
            messages.success(request, 'Perfil atualizado com sucesso')
        else:
            messages.error(request, 'Erro na atualização do Lojista')
    else:
        instance = get_object_or_404(Lojista, IELojista=ielojista)
        lojista_form = LojistaRegistrationForm(instance=instance)
    return render(request, 'lojista/edit.html', {'lojista_form': lojista_form})

@login_required
@user_passes_test(lambda u: u.is_superuser)
def lojistalist(request):
    lojistas = Lojista.objects.all()
    return render(request, 'lojista/list_lojistas.html', {'section': 'listar-lojistas',
                                                      'lojistas': lojistas})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def registeratividade(request):
    if request.method == 'POST':
        ramoatividade_form = RamoAtividadeRegistrationForm(request.POST)

        if ramoatividade_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_ramoatividade = ramoatividade_form.save(commit=False)
            # Save the User object
            new_ramoatividade.save()
            return render(request,
                          'lojista/register_ramo_atividade_done.html',
                          {'new_ramoatividade': new_ramoatividade})
    else:
        ramoatividade_form = RamoAtividadeRegistrationForm()
    return render(request, 'lojista/register_ramo_atividade.html', {'ramoatividade_form': ramoatividade_form})

@login_required
@user_passes_test(lambda u: u.is_superuser)
def listatividade(request):
    ramosatividade = RamoAtividade.objects.all()
    return render(request, 'lojista/list_ramo_atividade.html', {'section': 'ramoatividade',
                                                      'ramosatividade': ramosatividade})

liquida2018/lojista/templates/lojista/cupons.html
{% extends 'base.html' %}

{% block content %}
<h1>{{user.nome}}</h1>
{% for cupom in cupons %}
<div class="panel panel-success col-sm-2 col-md-2">
  <div class="card text-white text-center bg-secondary mb-3" style="max-width: 18rem;">
    <div class="card-header"> <strong>{{cupom.id}}</strong> </div>
    <div class="card-body">
      <h5 class="card-title">Cupom</h5>
      <p class="card-text">
        <h4>Documento Fiscal: <strong> {{cupom.documentoFiscal.numeroDocumento }}</strong></h3>
        <h4>Loja: <strong>{{cupom.documentoFiscal.lojista.fantasiaLojista }}</strong></h3>
        <h4>Data da compra: <strong>{{cupom.documentoFiscal.dataDocumento|date:"d/m/Y" }}</strong> </h3>
        <h4>Vendedor: <strong>{{cupom.documentoFiscal.vendedor }}</strong></h3>
        <h4>Cupom gerado: <strong>{{cupom.dataCriacao|date:"d/m/Y" }}</strong></h3>

      </p>
    </div>
  </div>
</div>
  {% endfor %}
{% endblock %}

liquida2018/lojista/templates/lojista/dashboard.html
{% extends "base.html" %}
{% load auth_extras %}
{% block title %}Liquida 2018{% endblock %}

{% block content %}

    <h1>Participantes</h1>
    <p>
      <a type="button" id="mymodal" class="btn btn-primary btn-lg" data-toggle="modal" href="{% url "participante:register-op" %}">
        Adicionar Participante <span class="glyphicon glyphicon-plus"></span>
      </a>
      <a type="button" id="mymodal" class="btn btn-secondary btn-lg" data-toggle="modal" href="{% url "participante:search" %}">
        Ver Participantes <span class="glyphicon glyphicon-user"></span>
      </a>
      <a type="button" id="mymodal" class="btn btn-info btn-lg" data-toggle="modal" href="{% url "participante:search_by_cpf" %}">
        Buscar participante <span class="glyphicon glyphicon-search"></span>
      </a>
    </p>

    <h1>Lojistas</h1>
    <p>
      <a type="button" id="mymodal" class="btn btn-primary btn-lg" data-toggle="modal" href="{% url "lojista:register" %}">
        Adicionar Lojistas <span class="glyphicon glyphicon-plus"></span>
      </a>
      <a type="button" id="mymodal" class="btn btn-secondary btn-lg" data-toggle="modal" href="{% url "lojista:list" %}">
        Ver lojistas <span class="glyphicon glyphicon-home">
      </a>
    </p>
    <h1>Ramos de atividades</h1>
    <p>
      <a type="button" id="mymodal" class="btn btn-primary btn-lg" data-toggle="modal" href="{% url "lojista:registeratividade" %}">
      Adicionar Ramo de atividade <span class="glyphicon glyphicon-plus"></span>
      </a>
      <a type="button" id="mymodal" class="btn btn-secondary btn-lg" data-toggle="modal" href="{% url "lojista:listatividade" %}">
        Ver Ramos de atividade <span class="glyphicon glyphicon-tag">
      </a>
    </p>

{% endblock %}

liquida2018/lojista/templates/lojista/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Editar Lojista{% endblock %}

{% block content %}
    <h1>Editar Lojista</h1>
    <p>Por favor, preencha os seguintes dados para editar o perfil do lojista:</p>

    <form action="." method="post" class="form-group">
      <div class="container-fluid col-md-6">
        {% bootstrap_form  lojista_form layout='horizontal' show_help=False %}
      </div>

        {% csrf_token %}
        <p><input type="submit" class="btn btn-primary btn-lg" value="Salvar">
            <a type="button" class="btn" href="{% url 'lojista:homepage' %}">Cancelar</button></p>
    </form>
{% endblock %}

liquida2018/lojista/templates/lojista/list_lojistas.html
{% extends "base.html" %}

{% block title %}Lojistas{% endblock %}

{% block content %}
    <h1>Lojistas cadastrados</h1>
    <div id="user-list">
        {% for lojista in lojistas %}
            <div class="user">
                <a href="#"><h2>nome: {{ lojista.fantasiaLojista }}</h2></a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

liquida2018/lojista/templates/lojista/list_ramo_atividade.html
{% extends "base.html" %}

{% block title %}Ramos de Atividade{% endblock %}

{% block content %}
    <h1>Ramos de Atividade cadastrados</h1>
    <div id="user-list">
        {% for ramoatividade in ramosatividade %}
            <div class="user">
                <a href="#"><h2>nome: {{ ramoatividade.atividade }}</h2></a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

liquida2018/lojista/templates/lojista/lojistas_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load widget_tweaks %}

{% block content %}
  <form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Filtro</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.CNPJLojista.label_tag }}
          {% render_field filter.form.CNPJLojista class="form-control cnpj" %}
        </div>
        <button type="submit" class="btn btn-primary">
          <span class="glyphicon glyphicon-search"></span> Buscar
        </button>
      </div>
    </div>
  </form>
<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Nome Fantasia</th>
        <th>CNPJ do Lojista</th>
        <th>Inscrição Estadual</th>
        <th>Ramo de Atividade</th>
      </tr>
    </thead>
    <tbody>
      {% for lojista in filter.qs %}
        <tr>
          <td>{{ lojista.fantasiaLojista }}</td>
          <td><a href="{{ lojista.get_absolute_url }}">{{ lojista.CNPJLojista }}</a></td>
          <td>{{ lojista.IELojista }}</td>
          <td>{{ lojista.ramoAtividade }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No data</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

liquida2018/lojista/templates/lojista/old_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css">
    <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Mrs+Sheppards%7CDosis:300,400,700%7COpen+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800;' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.min.css" %}" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static "css/animate.min.css" %}" type="text/css">
    <!-- Custom CSS -->
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}" type="text/css">


</head>
<body>
    <div id="header">
        {% if request.user.is_authenticated %}
        <span class="logo"><a href="{% url "dashboard" %}"><img src="{% static "img/image.png" %}" alt="liquida" id="logo" class="img-responsive"></a></span>
        {% else %}
        <span class="logo"><a href="{% url "homepage" %}"><img src="{% static "img/image.png" %}" alt="liquida" id="logo" class="img-responsive"></a></span>
        {% endif %}
        {% if request.user.is_authenticated %}

        <ul class="menu">

            <li {% if section == "dashboard" %}class="selected"{% endif %}><a href="{% url "dashboard" %}">Minha Conta</a></li>
            <li {% if section == "docsfiscais" %}class="selected"{% endif %}><a href="{% url "docsfiscais" %}">Documentos Fiscais</a></li>
            <li {% if section == "coupons" %}class="selected"{% endif %}><a href="{% url "coupons" %}">Cupons</a></li>
            <li {% if section == "premios" %}class="selected"{% endif %}><a href="{% url "premios" %}">Premios</a></li>
        </ul>
        {% endif %}

        <span class="user">
        {% if request.user.is_authenticated %}
            Olá {{ request.user.first_name }}, <a href="{% url "logout" %}">Sair</a>
        {% else %}
            <a class="btn btn-primary btn-lg" href="{% url "login" %}">Entrar</a>
        {% endif %}
        </span>
    </div>


    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">×</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <!-- jQuery -->
    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/parallax.js" %}"></script>
    <script src="{% static "js/contact.js" %}"></script>
    <script src="{% static "js/countto.js" %}"></script>
    <script src="{% static "js/jquery.easing.min.js" %}"></script>
    <script src="{% static "js/wow.min.js" %}"></script>
    <script src="{% static "js/common.js" %}"></script>
</body>
</html>

liquida2018/lojista/templates/lojista/register.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Adicionar Lojista{% endblock %}

{% block content %}
    <h1>Adicionar Lojista</h1>
    <p>Por favor, preencha os seguintes dados para efetuar o seu cadastro de um novo lojista:</p>

    <form action="." method="post" class="form-group">
      <div class="container-fluid col-md-6">
        {% bootstrap_field  lojista_form.CNPJLojista layout='horizontal' show_help=False %}
        {% bootstrap_field  lojista_form.IELojista layout='horizontal' show_help=False %}
        {% bootstrap_field  lojista_form.fantasiaLojista layout='horizontal' show_help=False %}
        {% bootstrap_field  lojista_form.razaoLojista layout='horizontal' show_help=False %}
        {% bootstrap_field  lojista_form.ramoAtividade layout='horizontal' show_help=False addon_after='<a data-toggle="modal" href="#novoRamo" class="btn btn-secondary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></a>' addon_after_class='input-group-btn' %}

        {% csrf_token %}
        <input type="submit" class="btn btn-primary btn-lg" value="Salvar">
            <a type="button" class="btn" href="{% url 'lojista:homepage' %}">Cancelar</button>
      </div>
    </form>
{% endblock %}

liquida2018/lojista/templates/lojista/register_done.html
{% extends "base.html" %}

{% block title %}Lojista adicionado{% endblock %}

{% block content %}
    <h1>O lojista {{ new_lojista.fantasiaLojista }} adicionado com sucesso!</h1>
    <p>Perfil de logista criado.</p>
    <p><a type="button" id="mymodal" class="btn btn-primary btn-lg" data-toggle="modal" href="{% url "lojista:register" %}">
  Adicionar outro perfil de lojista
</a><a type="button" class="btn" href="{% url 'lojista:homepage' %}">Voltar</button></p>
{% endblock %}

liquida2018/lojista/templates/lojista/register_ramo_atividade.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Adicionar Ramo de Atividade{% endblock %}

{% block content %}
    <h1>Adicionar Ramo de Atividade</h1>
    <p>Por favor, preencha os seguintes dados para efetuar o cadastro de um novo ramo de atividade:</p>
    <form action="." method="post" class="form-group">
      <div class=".container-fluid col-md-6">
        {% bootstrap_form ramoatividade_form layout='horizontal' exclude='ativo' %}
      </div>

        {% csrf_token %}
        <p><input type="submit" class="btn btn-primary btn-lg" value="Salvar">
            <a type="button" class="btn" href="{% url 'lojista:homepage' %}">Cancelar</button></p>
    </form>
{% endblock %}

liquida2018/lojista/templates/lojista/register_ramo_atividade_done.html
{% extends "base.html" %}

{% block title %}Ramo de atividade adicionado{% endblock %}

{% block content %}
    <h1>Ramo de atividade {{ new_ramoatividade.atividade }} adicionado com sucesso!</h1>
    <p>Ramo de atividade criado.</p>
    <p><a type="button" id="mymodal" class="btn btn-primary btn-lg" data-toggle="modal" href="{% url "lojista:registeratividade" %}">
  Adicionar outro ramo de atividade
</a><a type="button" class="btn" href="{% url 'lojista:homepage' %}">Voltar</button></p>
{% endblock %}

liquida2018/lojista/templates/lojista/search_by_cpf.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
<h1>Buscar pelo CPF do participante</h1>
<form method="get" class="form-group">
  <div class="container-fluid col-md-3">
      <input type="text" name="q" class="form-control cpf" placeholder="XXX.XXX.XXX-XX">
      <p><input type="submit" class="btn btn-primary btn-lg" value="Buscar">
      <a type="button" class="btn" href="{% url 'lojista:homepage' %}">Voltar</button></p>
    </div>
</form>


{% endblock %}