liquida2018/bcp/urls.py
"""
Module: Barcode Printer URLS
Project: Django BCP
Copyright: Adlibre Pty Ltd 2012
License: See LICENSE for license information
"""

from django.conf.urls import url
from . import views
from django.contrib.auth.views import *
from django.urls import path, re_path
#import mdtui.views

app_name = 'bcp'

urlpatterns = [
    re_path(r'^(?P<numerodocumento>[-\w]+)/(?P<code>[\w-]+)$', views.generate, name='generate'),
    re_path(r'^(?P<barcode_type>(Standard39|Code128))/(?P<code>[\w-]+)/print$', views.print_barcode, name='print'),
    re_path(r'^(?P<numerodocumento>[-\w]+)/(?P<code>[\w-]+)/print_qrcode$', views.print_qrcode, name='print_qrcode'),
    re_path(r'^(?P<barcode_type>(Standard39|Code128))/(?P<code>[\w-]+)/test', views.print_barcode_embed_example, name='embed-example'),
]

liquida2018/liquida2018/urls.py
"""liquida2018 URL Configuration
"""
from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from participante import urls as purls
from lojista import urls as lurls
from cupom import urls as curls
from bcp import urls as burls

handler404 = 'participante.views.not_found_page_view'

urlpatterns = [
    path('', include(purls)),
    path('nimda/', admin.site.urls),
    url('cupom/', include(curls, namespace='cupom')),
    path('lojista/', include(lurls, namespace='lojista')),
    path('barcode/', include(burls, namespace='bcp')),
    # python-social-auth
    #url('social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

liquida2018/lojista/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views
from django_filters.views import FilterView
from .filters import LojistaFilter

app_name = 'lojista'

urlpatterns = [
    # Lojistas urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('list/', views.lojistalist, name='list'),
    re_path(r'^edit/(?P<ielojista>[\d,.?!]+)/$', views.editlojista, name='editlojista'),
    # path('search/', FilterView.as_view(filterset_class=LojistaFilter,
    #     template_name='lojista/lojistas_list.html'), name='search'),
    path('search/', views.search, name='search'),
    path('cupons/', views.cupons, name='cupons'),
    #re_path(r'^search/(?P<cpf>[-\w]+)$', views.search_cpf, name='searchbycpf'),
    # Ramo de atividades pathpatterns
    path('registeratividade/', views.registeratividade, name='registeratividade'),
    path('listatividade/', views.listatividade, name='listatividade'),
]

liquida2018/participante/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import *
from django.urls import path, re_path
from django_filters.views import FilterView
from .filters import UserFilter
from .models import Profile


app_name = 'participante'
handler404 = 'views.not_found_page_view'

urlpatterns = [
    # url(r'^login/$', views.user_login, name='login'),
    path('', views.homepage, name='homepage'),
    path('dash/', views.dashboard, name='dashboard'),
    #path('lojista/', views.lojista, name='notfound'),
    # path('search/', FilterView.as_view(filterset_class=UserFilter,
    #     template_name='participante/participante_list.html'), name='search'),
    path('search/', views.search, name='search'),
    path('participante/cpf', views.search_by_cpf, name='search_by_cpf'),

    url(r'^list$', views.participante_list, name='list'),


    re_path(r'^participante/(?P<username>[-\w]+)/detail$', views.user_detail, name='user_detail'),
    re_path(r'^participante/edit/(?P<username>[-\w]+)/$', views.user_edit, name='user_edit'),
    # Coupons paths
    path('docsfiscais/', views.doclist, name='docsfiscais'),

    # Coupons paths
    path('coupons/', views.coupons, name='coupons'),

    # Premios paths
    path('premios/', views.premios, name='premios'),


    path('cadastrar/', views.register, name='register'),
    path('register/', views.register2, name='register-op'),
    path('edit/', views.edit, name='edit'),

    # Documentos Fiscais paths
    path('adddocfiscal/', views.adddocfiscal, name='adddocfiscal'),
    re_path(r'^adddocfiscal/(?P<username>[-\w]+)/$', views.adddocfiscalbyop, name='adddocfiscalbyop'),
    path('editdocfiscal/', views.editdocfiscal, name='editdocfiscal'),
    re_path(r'^editdocfiscal/(?P<numerodocumento>[\d,.?!]+)/$', views.editdocfiscal, name='editdocfiscal'),
    re_path(r'^validadocfiscal/(?P<numerodocumento>[\d,.?!]+)/$', views.validadocfiscal, name='validadocfiscal'),

    # login / logout paths
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('logout-then-login/', logout_then_login, name='logout_then_login'),

    # change password paths
    path('password-change/',password_change, name='password_change'),
    path('password-change/done/', password_change_done, name='password_change_done'),

    # restore password paths
    path('password-reset/', password_reset, name='password_reset'),
    path('password-reset/done/', password_reset_done, name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', password_reset_confirm, name='password_reset_confirm'),
    path('password-reset/complete/', password_reset_complete, name='password_reset_complete'),


]

liquida2018/participante/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from .models import Profile, DocumentoFiscal
from lojista.models import Lojista
from .filters import UserFilter, DocFilter
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models.functions import Lower, Upper
from cupom.forms import AddCupomForm
from cupom.models import Cupom

def not_found_page_view(request):
    return render(request, 'not_found.html')

@login_required
@user_passes_test(lambda u: u.is_superuser)
def search(request):
      user_list = Profile.objects.all().order_by(Upper('nome').asc())
      user_filter = UserFilter(request.GET, queryset=user_list)
      return render(request, 'participante/participante_list.html', {'filter': user_filter,
                                                                     'section':'participantes'})

def search_by_cpf(request):
    if(request.GET.get('q')):
        if 'q' in request.GET is not None:
            cpf = request.GET.get('q')
            profile = get_object_or_404(Profile, CPF=cpf)
            user = get_object_or_404(User, username= profile.user.username)
            docs = DocumentoFiscal.objects.filter(user=user)
            return render(request, 'participante/detail.html', {'section': 'people','user': profile, 'docs': docs})
        else:
            messages.error(request, 'CPF não encontrado!')
    return render(request, 'participante/search_by_cpf.html')

def participante_list(request):
    f = ParticipanteFilter(request.GET, queryset=Profile.objects.all())
    return render(request, 'participante/template.html', {'filter': f})

def register2(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileRegistrationForm(request.POST,
                                              files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            # Create the user profile
            new_profile = profile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return render(request,
                          'participante/register_done2.html',
                          {'new_user': new_profile})
    else:
        user_form = UserRegistrationForm()
        profile_form = ProfileRegistrationForm()
    return render(request, 'participante/register.html', {'user_form': user_form, 'profile_form': profile_form})

def homepage(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active and user.is_superuser:
                    login(request, user)
                    return render(request, 'lojista/dashboard.html')
                elif user.is_active:
                    login(request, user)
                    return render(request, 'participante/dashboard.html')
            else:
                login_form = LoginForm()
                return render(request, 'participante/index.html', {'section': 'homepage', 'lf': login_form})
    else:
        login_form = LoginForm()
    return render(request, 'participante/index.html', {'section': 'homepage', 'lf': login_form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Autenticado com sucesso!')
                else:
                    return HttpResponse('Conta desativada!')
            else:
                return HttpResponse('Login inválido!')
    else:
        form = LoginForm()
    return render(request, 'participante/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileRegistrationForm(request.POST,
                                              files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            # Create the user profile
            new_profile = profile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return render(request,
                          'participante/register_done.html',
                          {'new_user': new_profile})
    else:
        user_form = UserRegistrationForm()
        profile_form = ProfileRegistrationForm()
    return render(request, 'participante/register2.html', {'user_form': user_form, 'profile_form': profile_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Perfil atualizado com sucesso')
        else:
            messages.error(request, 'Erro na atualização do perfil')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'participante/edit.html', {'user_form': user_form,
                                                 'profile_form': profile_form})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    profile = get_object_or_404(Profile, user=user)
    docs_list = DocumentoFiscal.objects.filter(user=user)
    return render(request, 'participante/detail.html', {'section': 'people','user': profile, 'docs': docs_list})

@login_required
@user_passes_test(lambda u: u.is_superuser)
def user_edit(request, username):
    if request.method == 'POST':
        instance_user = get_object_or_404(User, username=username)
        instance_profile = get_object_or_404(Profile, user=instance_user)
        profile_form = ProfileEditForm(instance=instance_profile,
                                        data=request.POST,
                                        files=request.FILES)

        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Participante validado com sucesso')
        else:
            messages.error(request, 'Erro na validação do Participante')
    else:
        instance_user = get_object_or_404(User, username=username)
        instance_profile = get_object_or_404(Profile, user=instance_user)
        profile_form = ProfileEditForm(instance=instance_profile)
    return render(request, 'participante/editbyoperador.html', {'profile_form': profile_form})

@login_required
def adddocfiscal(request):
    if request.method == 'POST':
        documentoFiscal_form = UserAddFiscalDocForm(request.POST,
                                                    files=request.FILES)
        cnpj = documentoFiscal_form['lojista_cnpj'].value()
        lojista = get_object_or_404(Lojista, CNPJLojista=cnpj)
        user = request.user
        if documentoFiscal_form.is_valid():
            # Create a new document object but avoid saving it yet
            new_documentoFiscal = documentoFiscal_form.save(commit=False)
            # Set the user
            new_documentoFiscal.user = user
            new_documentoFiscal.lojista = lojista
            # Save the doc object
            new_documentoFiscal.save()
            return render(request,
                          'participante/doc_fiscal_done.html',
                          {'new_documentoFiscal': new_documentoFiscal})
    else:
        documentoFiscal_form = UserAddFiscalDocForm()
    return render(request, 'participante/doc_fiscal_add.html', {'documentoFiscal_form': documentoFiscal_form})

@login_required
def adddocfiscalbyop(request, username):
    if request.method == 'POST':
        documentoFiscal_form = UserAddFiscalDocForm(request.POST,
                                                    files=request.FILES)
        cnpj = documentoFiscal_form['lojista_cnpj'].value()
        lojista = get_object_or_404(Lojista, CNPJLojista=cnpj)
        user = get_object_or_404(User, username=username)
        if documentoFiscal_form.is_valid():
            # Create a new document object but avoid saving it yet
            new_documentoFiscal = documentoFiscal_form.save(commit=False)
            # Set the user
            new_documentoFiscal.user = user
            new_documentoFiscal.lojista = lojista
            # Save the doc object
            new_documentoFiscal.save()
            return render(request,
                          'participante/doc_fiscal_done_op.html',

liquida2018/participante/templates/base.html
{% load staticfiles %}
{% load auth_extras %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap Core CSS -->

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css">

    <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Mrs+Sheppards%7CDosis:300,400,700%7COpen+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800;' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.min.css" %}" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static "css/animate.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/select2.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/perfect-scrollbar.css" %}" type="text/css">
    <!-- Custom CSS -->
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}" type="text/css">
    <!-- <link rel="stylesheet" href="{% static "css/main.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/util.css" %}" type="text/css"> -->


</head>
<body>
    <div id="header">
        {% if request.user.is_authenticated %}
        <span class="logo"><a href="{% url "participante:dashboard" %}">Liquida Teresina 2018</a></span>
        {% else %}
        <span class="logo"><a href="{% url "participante:homepage" %}">Liquida Teresina 2018</a></span>
        {% endif %}
        {% if request.user.is_authenticated %}
        <ul class="menu">
          {% if request.user.is_superuser %}
          <li {% if section == "lojista" %}class="selected"{% endif %}><a href="{% url "lojista:homepage" %}">Lojistas</a></li>
          <li {% if section == "lojistas" %}class="selected"{% endif %}><a href="{% url "lojista:search" %}">Listar Lojistas</a></li>
          <li {% if section == "participantes" %}class="selected"{% endif %}><a href="{% url "participante:search" %}">Participantes</a></li>
          <li {% if section == "Cupons" %}class="selected"{% endif %}><a href="{% url "lojista:cupons" %}">Cupons Gerados</a></li>
          {% else %}
            <li {% if section == "dashboard" %}class="selected"{% endif %}><a href="{% url "participante:dashboard" %}">Minha Conta</a></li>
            <li {% if section == "docsfiscais" %}class="selected"{% endif %}><a href="{% url "participante:docsfiscais" %}">Documentos Fiscais</a></li>
            <li {% if section == "coupons" %}class="selected"{% endif %}><a href="{% url "participante:coupons" %}">Cupons</a></li>
            <li {% if section == "premios" %}class="selected"{% endif %}><a href="{% url "participante:premios" %}">Premios</a></li>
          {% endif %}
          </ul>
        {% endif %}

        <span class="user">
        {% if request.user.is_authenticated %}
            Olá {{ request.user.username }}, <a href="{% url "participante:logout" %}">Sair</a>
        {% else %}
            <a  href="{% url "participante:login" %}">Entrar</a>
        {% endif %}
        </span>
    </div>


    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">×</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <!-- jQuery -->
    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/parallax.js" %}"></script>
    <script src="{% static "js/contact.js" %}"></script>
    <script src="{% static "js/countto.js" %}"></script>
    <script src="{% static "js/jquery.easing.min.js" %}"></script>
    <script src="{% static "js/wow.min.js" %}"></script>
    <script src="{% static "js/common.js" %}"></script>
    <script src="{% static "js/jquery.mask.min.js" %}"></script>
    <script src="{% static "js/jquery.mask.js" %}"></script>
    <script src="{% static "js/masks.js" %}"></script>
    <script src="{% static "js/select2.min.js" %}"></script>
    <script src="{% static "js/popper.js" %}"></script>
</body>
</html>

liquida2018/participante/templates/not_found.html
{% extends "base.html" %}

{% block title %}Nao encontrado{% endblock %}

{% block content %}
    <h1>Nao encontrado!</h1>
{% endblock %}