liquida2018/bcp/urls.py
"""
Module: Barcode Printer URLS
Project: Django BCP
Copyright: Adlibre Pty Ltd 2012
License: See LICENSE for license information
"""

from django.conf.urls import url
from . import views
from django.contrib.auth.views import *
from django.urls import path, re_path
#import mdtui.views

app_name = 'bcp'

urlpatterns = [
    re_path(r'^(?P<numerodocumento>[-\w]+)/(?P<code>[\w-]+)$', views.generate, name='generate'),
    re_path(r'^(?P<barcode_type>(Standard39|Code128))/(?P<code>[\w-]+)/print$', views.print_barcode, name='print'),
    re_path(r'^(?P<numerodocumento>[-\w]+)/(?P<code>[\w-]+)/print_qrcode$', views.print_qrcode, name='print_qrcode'),
    re_path(r'^(?P<barcode_type>(Standard39|Code128))/(?P<code>[\w-]+)/test', views.print_barcode_embed_example, name='embed-example'),
]

liquida2018/liquida2018/urls.py
"""liquida2018 URL Configuration
"""
from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from participante import urls as purls
from lojista import urls as lurls
from cupom import urls as curls
from bcp import urls as burls

handler404 = 'participante.views.not_found_page_view'

urlpatterns = [
    path('', include(purls)),
    path('nimda/', admin.site.urls),
    url('cupom/', include(curls, namespace='cupom')),
    path('lojista/', include(lurls, namespace='lojista')),
    path('barcode/', include(burls, namespace='bcp')),
    # python-social-auth
    #url('social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

liquida2018/participante/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import *
from django.urls import path, re_path
from django_filters.views import FilterView
from .filters import UserFilter
from .models import Profile


app_name = 'participante'
handler404 = 'views.not_found_page_view'

urlpatterns = [
    # url(r'^login/$', views.user_login, name='login'),
    path('', views.homepage, name='homepage'),
    path('dash/', views.dashboard, name='dashboard'),
    #path('lojista/', views.lojista, name='notfound'),
    # path('search/', FilterView.as_view(filterset_class=UserFilter,
    #     template_name='participante/participante_list.html'), name='search'),
    path('search/', views.search, name='search'),
    path('participante/cpf', views.search_by_cpf, name='search_by_cpf'),

    url(r'^list$', views.participante_list, name='list'),


    re_path(r'^participante/(?P<username>[-\w]+)/detail$', views.user_detail, name='user_detail'),
    re_path(r'^participante/edit/(?P<username>[-\w]+)/$', views.user_edit, name='user_edit'),
    # Coupons paths
    path('docsfiscais/', views.doclist, name='docsfiscais'),

    # Coupons paths
    path('coupons/', views.coupons, name='coupons'),

    # Premios paths
    path('premios/', views.premios, name='premios'),


    path('cadastrar/', views.register, name='register'),
    path('register/', views.register2, name='register-op'),
    path('edit/', views.edit, name='edit'),

    # Documentos Fiscais paths
    path('adddocfiscal/', views.adddocfiscal, name='adddocfiscal'),
    re_path(r'^adddocfiscal/(?P<username>[-\w]+)/$', views.adddocfiscalbyop, name='adddocfiscalbyop'),
    path('editdocfiscal/', views.editdocfiscal, name='editdocfiscal'),
    re_path(r'^editdocfiscal/(?P<numerodocumento>[\d,.?!]+)/$', views.editdocfiscal, name='editdocfiscal'),
    re_path(r'^validadocfiscal/(?P<numerodocumento>[\d,.?!]+)/$', views.validadocfiscal, name='validadocfiscal'),

    # login / logout paths
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('logout-then-login/', logout_then_login, name='logout_then_login'),

    # change password paths
    path('password-change/',password_change, name='password_change'),
    path('password-change/done/', password_change_done, name='password_change_done'),

    # restore password paths
    path('password-reset/', password_reset, name='password_reset'),
    path('password-reset/done/', password_reset_done, name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', password_reset_confirm, name='password_reset_confirm'),
    path('password-reset/complete/', password_reset_complete, name='password_reset_complete'),


]

liquida2018/participante/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from .models import Profile, DocumentoFiscal
from lojista.models import Lojista
from .filters import UserFilter, DocFilter
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models.functions import Lower, Upper
from cupom.forms import AddCupomForm
from cupom.models import Cupom

def not_found_page_view(request):
    return render(request, 'not_found.html')

@login_required
@user_passes_test(lambda u: u.is_superuser)
def search(request):
      user_list = Profile.objects.all().order_by(Upper('nome').asc())
      user_filter = UserFilter(request.GET, queryset=user_list)
      return render(request, 'participante/participante_list.html', {'filter': user_filter,
                                                                     'section':'participantes'})

def search_by_cpf(request):
    if(request.GET.get('q')):
        if 'q' in request.GET is not None:
            cpf = request.GET.get('q')
            profile = get_object_or_404(Profile, CPF=cpf)
            user = get_object_or_404(User, username= profile.user.username)
            docs = DocumentoFiscal.objects.filter(user=user)
            return render(request, 'participante/detail.html', {'section': 'people','user': profile, 'docs': docs})
        else:
            messages.error(request, 'CPF não encontrado!')
    return render(request, 'participante/search_by_cpf.html')

def participante_list(request):
    f = ParticipanteFilter(request.GET, queryset=Profile.objects.all())
    return render(request, 'participante/template.html', {'filter': f})

def register2(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileRegistrationForm(request.POST,
                                              files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            # Create the user profile
            new_profile = profile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return render(request,
                          'participante/register_done2.html',
                          {'new_user': new_profile})
    else:
        user_form = UserRegistrationForm()
        profile_form = ProfileRegistrationForm()
    return render(request, 'participante/register.html', {'user_form': user_form, 'profile_form': profile_form})

def homepage(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active and user.is_superuser:
                    login(request, user)
                    return render(request, 'lojista/dashboard.html')
                elif user.is_active:
                    login(request, user)
                    return render(request, 'participante/dashboard.html')
            else:
                login_form = LoginForm()
                return render(request, 'participante/index.html', {'section': 'homepage', 'lf': login_form})
    else:
        login_form = LoginForm()
    return render(request, 'participante/index.html', {'section': 'homepage', 'lf': login_form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Autenticado com sucesso!')
                else:
                    return HttpResponse('Conta desativada!')
            else:
                return HttpResponse('Login inválido!')
    else:
        form = LoginForm()
    return render(request, 'participante/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileRegistrationForm(request.POST,
                                              files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            # Create the user profile
            new_profile = profile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return render(request,
                          'participante/register_done.html',
                          {'new_user': new_profile})
    else:
        user_form = UserRegistrationForm()
        profile_form = ProfileRegistrationForm()
    return render(request, 'participante/register2.html', {'user_form': user_form, 'profile_form': profile_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Perfil atualizado com sucesso')
        else:
            messages.error(request, 'Erro na atualização do perfil')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'participante/edit.html', {'user_form': user_form,
                                                 'profile_form': profile_form})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    profile = get_object_or_404(Profile, user=user)
    docs_list = DocumentoFiscal.objects.filter(user=user)
    return render(request, 'participante/detail.html', {'section': 'people','user': profile, 'docs': docs_list})

@login_required
@user_passes_test(lambda u: u.is_superuser)
def user_edit(request, username):
    if request.method == 'POST':
        instance_user = get_object_or_404(User, username=username)
        instance_profile = get_object_or_404(Profile, user=instance_user)
        profile_form = ProfileEditForm(instance=instance_profile,
                                        data=request.POST,
                                        files=request.FILES)

        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Participante validado com sucesso')
        else:
            messages.error(request, 'Erro na validação do Participante')
    else:
        instance_user = get_object_or_404(User, username=username)
        instance_profile = get_object_or_404(Profile, user=instance_user)
        profile_form = ProfileEditForm(instance=instance_profile)
    return render(request, 'participante/editbyoperador.html', {'profile_form': profile_form})

@login_required
def adddocfiscal(request):
    if request.method == 'POST':
        documentoFiscal_form = UserAddFiscalDocForm(request.POST,
                                                    files=request.FILES)
        cnpj = documentoFiscal_form['lojista_cnpj'].value()
        lojista = get_object_or_404(Lojista, CNPJLojista=cnpj)
        user = request.user
        if documentoFiscal_form.is_valid():
            # Create a new document object but avoid saving it yet
            new_documentoFiscal = documentoFiscal_form.save(commit=False)
            # Set the user
            new_documentoFiscal.user = user
            new_documentoFiscal.lojista = lojista
            # Save the doc object
            new_documentoFiscal.save()
            return render(request,
                          'participante/doc_fiscal_done.html',
                          {'new_documentoFiscal': new_documentoFiscal})
    else:
        documentoFiscal_form = UserAddFiscalDocForm()
    return render(request, 'participante/doc_fiscal_add.html', {'documentoFiscal_form': documentoFiscal_form})

@login_required
def adddocfiscalbyop(request, username):
    if request.method == 'POST':
        documentoFiscal_form = UserAddFiscalDocForm(request.POST,
                                                    files=request.FILES)
        cnpj = documentoFiscal_form['lojista_cnpj'].value()
        lojista = get_object_or_404(Lojista, CNPJLojista=cnpj)
        user = get_object_or_404(User, username=username)
        if documentoFiscal_form.is_valid():
            # Create a new document object but avoid saving it yet
            new_documentoFiscal = documentoFiscal_form.save(commit=False)
            # Set the user
            new_documentoFiscal.user = user
            new_documentoFiscal.lojista = lojista
            # Save the doc object
            new_documentoFiscal.save()
            return render(request,
                          'participante/doc_fiscal_done_op.html',

liquida2018/participante/templates/participante/coupons.html
{% extends "base.html" %}

{% block title %}Cupons{% endblock %}

{% block content %}
    <h1>Seus cupons</h1>
    <p>Aqui serão listados os cupons.</p>
{% endblock %}

liquida2018/participante/templates/participante/dashboard.html
{% extends "base.html" %}

{% block title %}Liquida 2018{% endblock %}

{% block content %}
    <h1>Liquida Teresina 2018</h1>
    <p>Bem vindo a sua conta do Liquida. Você pode <a href="{% url 'participante:edit' %}">editar o seu perfil</a> ou <a href="{% url 'participante:password_change' %}">mudar a sua senha</a>.</p>
    <a type="button" id="mymodal" class="btn btn-primary btn-lg" data-toggle="modal" href="{% url 'participante:adddocfiscal' %}">
  Adicionar documento fiscal
</a>
<br/>
<br/>
  <h1>Documentos Lançados</h1>
  <div id="doc-list" class="table-responsive">
    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>Número do Documento</th>
          <th>Loja</th>
          <th>Data da Compra</th>
          <th>Valor do documento</th>
          <th>Vendedor</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {% for doc in docs %}

            <tr>
              <td><a href="{{ doc.get_absolute_url }}">{{ doc.numeroDocumento }}</a></td>
              <td>{{ doc.lojista }}</td>
              <td>{{ doc.dataDocumento }}</td>
              <td>{{ doc.valorDocumento }}</td>
              <td>{{ doc.vendedor}}</td>
              <td>Pendente</td>
            </tr>

        {% empty %}
          <tr>
            <td colspan="5">Nenhum documento lançado</td>
          </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Novo cupom</h4>
  </div>
  <div class="modal-body">
    ...
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    <button type="button" class="btn btn-primary">Salvars</button>
  </div>
</div>
</div>
</div>

{% endblock %}

liquida2018/participante/templates/participante/detail2.html
{% extends "base.html" %}
{% load thumbnail %}
{% load bootstrap4 %}
{% block title %}{{ user.profile.nome }}{% endblock %}

{% block content %}
    <h1>{{ user.nome }}</h1>
    <div class="profile-info">
      {% thumbnail user.photo "100x100" crop="center" as im %}
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
  {% endthumbnail %}
    </div>

{% endblock %}

liquida2018/participante/templates/participante/doc_fiscal_add.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Adicionar documento fiscal{% endblock %}

{% block content %}
    <h1>Novo documento Fiscal</h1>
    <p>Você precisa preencher as seguinter informações referentes ao seu documento fiscal:</p>
    <form action="." method="post" enctype="multipart/form-data" class="form-group">
      <div class="container-fluid col-md-6">
          {% bootstrap_form documentoFiscal_form layout='horizontal' show_help=False exclude='status' %}

        </div>
        {% csrf_token %}
        <p><input type="submit" class="btn btn-primary btn-lg" value="Gravar">
        <a type="button" class="btn" href="{% url 'participante:dashboard' %}">Cancelar</button></p>
    </form>
{% endblock %}

liquida2018/participante/templates/participante/doc_fiscal_done_op.html
{% extends "base.html" %}

{% block title %}Documento fiscal lançado com sucesso!{% endblock %}

{% block content %}
    <h1>O documento numero <strong>{{ new_documentoFiscal.numeroDocumento }}</strong> foi lançado para o participante <strong> {{participante.username}}</strong>!</h1>
    <p><a type="button" id="mymodal" class="btn btn-primary btn-lg" data-toggle="modal" href="{% url "participante:adddocfiscal" %}{{participante.username}}">
  Adicionar outro documento fiscal
</a><a type="button" class="btn" href="{% url 'lojista:homepage' %}">Voltar para área de operação</button></p>

{% endblock %}

liquida2018/participante/templates/participante/doc_fiscal_edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Editar Documento{% endblock %}

{% block content %}
    <h1>Editar Documento Fiscal</h1>
    <p>Você pode editar as seguintes informações do seu documento:</p>
    <form action="." method="post" enctype="multipart/form-data"class="form-group">
      <div class="container-fluid col-md-6">
        {% bootstrap_form documentofiscal_form layout='horizontal' show_help=False exclude='status' %}
        </div>
        {% csrf_token %}
        <p><input type="submit" class="btn btn-primary btn-lg" value="Gravar">
        <a type="button" class="btn" href="{% url 'participante:dashboard' %}">Cancelar</button></p>
    </form>
{% endblock %}

liquida2018/participante/templates/participante/editbyoperador.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Editar perfil{% endblock %}

{% block content %}
    <h1>Editar perfil {{user_fom.username}}</h1>
    <p>Você pode editar as seguintes informações :</p>
    <form action="." method="post" enctype="multipart/form-data"class="form-group">
      <div class="container-fluid col-md-6">
        {% bootstrap_form profile_form layout='horizontal' show_help=False %}
      </div>
        {% csrf_token %}
        <p><input type="submit" class="btn btn-primary btn-lg" value="Salvar Alterações">
        <a type="button" class="btn" href="{% url 'participante:dashboard' %}">Cancelar</button></p>
    </form>
{% endblock %}

liquida2018/participante/templates/participante/login.html
{% extends "base.html" %}

{% block title %}Log-in{% endblock %}

{% block content %}
    <h1>Entrar</h1>
    <p>Por favor, use o seguinte formulario para logar no sistema:</p>
    <form action="." method="post">
        <!--{{ form.as_p }}-->
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            {{ form.username.errors }}
            <label for="{{ form.username.id_for_label }}">Usuario:</label>
            {{ form.username }}
        </div>
        <div class="fieldWrapper">
            {{ form.password.errors }}
            <label for="{{ form.password.id_for_label }}">Senha:</label>
            {{ form.password }}
        </div>
        {% csrf_token %}
        <p><input type="submit" value="Log-in"></p>
    </form>
{% endblock %}

liquida2018/participante/templates/participante/participante_list.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
  <form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Informe o CPF do participante</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.CPF.label_tag }}
          {% render_field filter.form.CPF class="form-control cpf" %}
        </div>
        <button type="submit" class="btn btn-primary">
          <span class="glyphicon glyphicon-search"></span> Buscar
        </button>
      </div>
    </div>
  </form>
<div class="table-responsive">
  <table class="table table-hover table-striped" >
    <thead>
      <tr>
        <th style="text-align: center; vertical-align:middle !important">Nome</th>
        <th style="text-align: center; vertical-align:middle !important">CPF</th>
        <th style="text-align: center; vertical-align:middle !important">Email</th>
        <th style="text-align: center; vertical-align:middle !important">Data de cadastro</th>
        <th style="text-align: center; vertical-align:middle !important">Pergunta</th>
        <th style="text-align: center; vertical-align:middle !important"></th>
      </tr>
    </thead>
    <tbody>
      {% for user in filter.qs %}
        <tr>
          <td style="text-align: center; vertical-align:middle !important">{{ user.nome|upper }}</td>
          <td style="text-align: center; vertical-align:middle !important">{{ user.CPF }}</td>
          <td style="text-align: center; vertical-align:middle !important">{{ user.user.email }}</td>
          <td style="text-align: center; vertical-align:middle !important">{{ user.dataCadastro|date:"d/m/Y" }}</td>
          <td style="text-align: center; vertical-align:middle !important">{{ user.pergunta}}</td>
          <td style="text-align: center; vertical-align:middle !important"><a data-toggle="modal" href="#{{ user.user.username }}"class="btn btn-primary a-btn-slide-text btn-sm">
        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <span><strong>Ver</strong></span> </a>
        <a href="{{ user.get_absolute_url_edit }}" class="btn btn-secondary a-btn-slide-text btn-sm">
          <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
          <span><strong>Editar</strong></span>
      </a>
      <a href="{% url 'participante:adddocfiscal' %}{{ user.user.username }}" class="btn btn-info a-btn-slide-text btn-sm">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        <span><strong>Lançar</strong></span>
    </a>
    </td>

          <!-- Modal -->
          <div class="modal fade" id="{{ user.user.username }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h2 class="modal-title" id="exampleModalLabel">{{ user.nome }}</h2>

                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>{{ user.CPF }}</p>
                  <p>{{ user.user.email }}</p>
                  <p>{{ user.dataCadastro }}</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                  <a type="button" class="btn btn-primary" href="{{ user.get_absolute_url_detail }}">Ver perfil</a>
                </div>
              </div>
            </div>
          </div>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">Nenhum participante encontrado</td>
        </tr>



      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

liquida2018/participante/templates/participante/premios.html
{% extends "base.html" %}

{% block title %}Premios{% endblock %}

{% block content %}
    <h1>Premios da promoção Liquida 2018</h1>
    <p>Aqui serão listados os Premios.</p>
{% endblock %}

liquida2018/participante/templates/participante/register.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}Criar a conta de participante{% endblock %}

{% block content %}
    <h1>Criar conta participante</h1>
    <p>Por favor, preencha os seguintes dados para efetuar o cadastro do participante:</p>
    <form action="." method="post">
      <div class="container-fluid col-md-6">
        {% bootstrap_form user_form layout='horizontal' %}
        {% bootstrap_form profile_form layout='horizontal' %}

        {% csrf_token %}
        <p><input type="submit" class="btn btn-primary btn-lg" value="Criar conta">
            <a type="button" class="btn" href="{% url 'participante:homepage'%}">Cancelar</button></p>
      </div>      
    </form>
{% endblock %}

liquida2018/participante/templates/participante/search_by_cpf.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
<h1>Buscar pelo CPF do participante</h1>
<form method="get" class="form-group">
  <div class="container-fluid col-md-3">
      <input type="text" name="q" class="form-control cpf" placeholder="XXX.XXX.XXX-XX">
      <p><input type="submit" class="btn btn-primary btn-lg" value="Buscar">
      <a type="button" class="btn" href="{% url 'lojista:homepage' %}">Voltar</button></p>
    </div>
</form>


{% endblock %}

liquida2018/participante/templates/participante/template.html
  <div class="container">
    <h1>Buscar por CPF</h1>
    <form action="/search/" method="post">
      {% csrf_token %}
      <div class="form-group">
        <div class="col-lg-5">
          <input type="text" name="srh" class="form-control" placeholder="Digite o CPF">
        </div>
        <label class="col-lg-2">
            <button type="submit" class="btn btn-danger">Buscar</button>
        </label>

      </div>
    </form>

  </div>